spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres?currentSchema=time_management_system
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true

        show_sql: true
        use_sql_comments: true
        format_sql: true

    hibernate:
      ddl-auto: update

    database: postgresql
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        SQL: debug

        orm:
          jdbc:
            bind: trace

        type:
          descriptor:
            sql:
              BasicBinder: trace




