version: '3'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    restart: always
    ports:
      - 5432:5433
    environment:
      - 'POSTGRES_USER=postgres'
      - 'PGUSER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=postgresql'
#    volumes:
#      - postgres:/var/lib/postgresql/data
#      - ./scripts/amend_user.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgresql" ]
      interval: 1s
      retries: 20

  app:
    image: spring
    container_name: spring
    build: ./
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?currentSchema=time_management_system