version: '3'

services:
  postgres:
    image: postgres:15.4
    container_name: postgres
    restart: always
    ports:
      - 5432:5433
    environment:
      - 'POSTGRES_USER=postgres'
      - 'PGUSER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=postgresql'

  server:
    image: spring
    container_name: spring
    build: ./backend-spring
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres

  client:
    image: react
    container_name: react
    build: ./frontend-react
    ports:
      - "3000:3000"
    depends_on:
      - server